@startuml

ComputeDarbouxFrame -> CollisionLineSearch
CollisionLineSearch -> NonemptyGrasp
NonemptyGrasp -> GraspSamplingAlgorithm
state GraspCandidate {
    state ComputeDarbouxFrame {
    }

    state CollisionLineSearch {
    }

    state NonemptyGrasp {

    }

    state GraspSamplingAlgorithm {
        
    }
}


GraspCandidate:Select a grasp pose using heuristic based on the local curvature

' (*) -> "Select a grasp pose using a\nheuristic based on the local\ncurvature"

' -r-> "Plan a grasp"
' -r-> "Move arm to grasp"
' -r-> "Force control"

@enduml
